const Demosites = [
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo31.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo4.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo6.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo23.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo10.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo25.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo2.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo17.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo5.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo22.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo9.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo13.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo28.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo11.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo19.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },

  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo24.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo12.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo15.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo7.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo8.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo18.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo29.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo14.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo16.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo20.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo1.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo27.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo26.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo21.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo30.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
  {
    id: Math.random(),
    _Img: "https://colabrio.ams3.cdn.digitaloceanspaces.com/ohio/landing/assets/img/new/Demo3.jpeg",
    title: "Digital Agency",
    category: "Agency,Studio.Portfolio",
  },
];

export default Demosites;
